changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

defaultSemverRangePrefix: ""

enableGlobalCache: true

nodeLinker: node-modules

preferInteractive: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
  os:
    - darwin
    - linux
