nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
  os:
    - darwin
    - linux

defaultSemverRangePrefix: ''
changesetBaseRefs:
  - 'main'
  - 'origin/main'
  - 'upstream/main'
preferInteractive: true
enableGlobalCache: true
