name: Assign Me to Feature
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  assign_me:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run gh issue edit "$NUMBER" --add-assignee @me
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        NUMBER: ${{ github.event.issue.number }}
